"""empty message

Revision ID: df90adc613be
Revises: 
Create Date: 2023-04-12 14:36:27.824037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df90adc613be'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url_2', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_url_3', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('image_url_4', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('image_url_4')
        batch_op.drop_column('image_url_3')
        batch_op.drop_column('image_url_2')

    # ### end Alembic commands ###
